version: '3.7'

services:
    server:
        image: peerjs/peerjs-server
        ports:
            - 9000:9000
    client:
        build:
            context: .
            target: development
        working_dir: /app
        volumes:
            - ./client:/app
        ports:
            - 9010:8080
        entrypoint:
            - "http-server"
            - "/app/dist"
        