version: '3.7'

services:
    server:
        image: peerjs/peerjs-server
        ports:
            - 9000:9000
    client:
        build:
            context: .
        volumes:
            - ./client:/app
        ports:
            - 9010:8080
