version: '3.7'

services:
    # server:
    #     image: peerjs/peerjs-server
    #     ports:
    #         - 9000:9000
    app:
        build:
            context: .
        working_dir: /app
        volumes:
            - ./app:/app
            - ./init.sh:/docker-entrypoint-initdb.d/init.sh
        ports:
            - 9010:8080
            - 9000:9000
        entrypoint:
            - /bin/sh
            - /docker-entrypoint-initdb.d/init.sh
        